POST http://localhost:9000/api/auth/login HTTP/1.1
content-type: application/json

{
    "userName": "admin",
    "userPassword": "pass"
}


###

POST http://localhost:9000/api/auth/register HTTP/1.1
content-type: application/json

{
    "userName": "matqw",
    "userEmail": "mateuszpiorowski12@gmail.com",
    "userPassword": "pass"
}


###

GET http://localhost:9000/api/auth/user HTTP/1.1
content-type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOTU0YzY4ZWItMDBmZC00YzQ3LWI3MzItNGQ5YjNjMzA2ZmRlIiwiaWF0IjoxNTkwNzYyMTIyLCJleHAiOjE1OTA4NDg1MjJ9.EJpg4HBeCW3yb7ff7nlQhKGDxSkZ6H90EIgUPX-ymcA