FROM node:13-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./tsconfig*.json ./

RUN npm install

COPY src src
COPY migrations migrations
COPY knexfile.ts knexfile.ts

RUN npm run tsc

# # Stage 2 - Create a downsized production container
# FROM node:13-alpine as production

# WORKDIR /usr/src/app

# COPY --from=builder /usr/src/app/build /usr/src/app